### ISSUE TITLE
map_handle is calling NtMapViewOfSection with an invalid ViewSize

### ISSUE THREAD

**Issue by BurningEnlightenment** [ned14/llfio#28]
map_handle calls [`NtMapViewOfSection()`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-zwmapviewofsection) API with a ViewSize (=`_bytes`) rounded up to the page size:
https://github.com/ned14/llfio/blob/adfce1788791f199940eabcfd65b2f4b6e5cdeb5/include/llfio/v2.0/detail/impl/windows/map_handle.ipp#L616-L619
This gets rejected with `0xC000001F | STATUS_INVALID_VIEW_SIZE` if the section reservation is not a multiple of the page size. `mapped_file()` unfortunately instructs the section_handle factory to set the section maximum size to the file extent...
However, from my underinformed point of view it seems unnecessary to manually round to the nearest page size as `NtMapViewOfSection()` does that anyways and even returns the result to us. Do you want me to make a PR to fix it?

**Comment by ned14** [comment]
I've learned from bitter experience that messing with this part of LLFIO without adding unit tests is very unwise. I vaguely remember that different errors pop out depending on what privs the handle has, so it may be that rounding to page size is not necessary for read-only section, but may be for read-write ones, and so on.

I'm sure that there is consistency in the NT kernel API on this, but it's not well documented, and I've not had the time to write a comprehensive set of LLFIO conformance tests to ensure that all combinations of file handle modes, section handle flags, and various sizes in and around a page size (including large and huge page sizes) all have reasonable behaviours and semantics, and on both Windows and Linux.

As you may have noticed, there is a comprehensive args permutation test framework in there, just somebody needs to think through all the possible combos, and write out the initialiser lists of all those combos. If you could help with that part, that would be *amazing*. As you may have noticed, due to lack of free time, LLFIO has not received much love recently. Writing WG21 papers and getting Outcome ready for Boost 1.71 have consumed all the free time I have.

**Comment by BurningEnlightenment** [comment]
> If you could help with that part, that would be amazing.

I will take a shot at it later this week.

> As you may have noticed, due to lack of free time, LLFIO has not received much love recently. Writing WG21 papers and getting Outcome ready for Boost 1.71 have consumed all the free time I have.

I fully understand that and there's nothing bad about it. I therefore try to reduce the overhead on your part as much as I can. If there is something I can improve with regard to that just tell me.

**Comment by ned14** [comment]
Fixed! Thanks for the BR.
