### ISSUE TITLE
Problems trying to build static library on Windows

### ISSUE THREAD

**Issue by cos-public** [ned14/llfio#31]
Repo path: c:\Users\username\lib\llfio-src

Executing:
git config --system core.longpaths true
git clone --recursive https://github.com/ned14/llfio.git llfio-src

results in:
...
error: Server does not allow request for unadvertised object 37d6d9f759aa5edcaea25ee459dc00db2c726ad8
Fetched in submodule path 'test/kerneltest/include/kerneltest/v1.0/outcome/doc/html', but it did not contain 37d6d9f759aa5edcaea25ee459dc00db2c726ad8. Direct fetching of that commit failed.
....
Failed to recurse into submodule path 'test/kerneltest/include/kerneltest/v1.0/outcome'
Failed to recurse into submodule path 'include/llfio/v2.0/outcome'
Failed to recurse into submodule path 'test/kerneltest'

**Comment by ned14** [comment]
Yes, this is a legacy of when I reset the history of the documentation submodule for outcome. It should be benign. If not, you can find a complete source tarball at https://dedi5.nedprod.com/static/files/llfio/

I am aware that LLFIO has become a bit neglected. That's because I'm in the process of upgrading its `path_view` and `signal_guard` to meet WG21 feedback, and it all happens outside of work. I should be done in the next few weeks. Can you wait until then?

**Comment by cos-public** [comment]
Yes, sure. No problem. Just wanted to report a problem a fresh user might encounter. I didn't spent much effort to overcome it. Will take a look later. Thanks.

**Comment by ned14** [comment]
FYI master and develop branch are now building on all platforms and passing all their unit tests on all platforms. Prebuilt binaries are being generated again.
