### ISSUE TITLE
Sync vs Async

### ISSUE THREAD

**Issue by zpyatt** [ned14/llfio#48]
Niall,

First thanks for the awesome library. It is truly amazing, I there was more support from Boost and/or the ISO committee. It seems strange to me there isn't more demand for this sort of thing. I'm trying to write 10 Gbit data to SSDs and this library is a god send.

I'm curious about using synchronous vs. asynchronous calls. In this reddit thread: https://www.reddit.com/r/cpp/comments/5s8s2f/is_there_efficient_alternative_to_asio/ you indicated sync. is more performant than async. I believe I've read this elsewhere but it seems to contradict everything else on the internet.  I'm inclined to believe you, after all you should know, but do you have any resources you could point me toward?

Also there is the issue of benchmark tools like CrystalMark or fio. They seem to indicate throughput is higher with higher queue depths (like Q32T1 or Q8T8). If I understand queue depths correctly they are basically outstanding async calls. Is this correct? If so why do drives perform better with these async calls than synchronous sequential calls? Also, how would vectorized (scatter/gather) i/o fit into this equation?

I'd like to label this as a question but couldn't figure out how.

Thanks.

**Comment by ned14** [comment]
WG21 are supportive so far: https://wg21.link/P1883 is onto R1, we shall see how https://wg21.link/P2052 fares.

> I'm curious about using synchronous vs. asynchronous calls. In this reddit thread: https://www.reddit.com/r/cpp/comments/5s8s2f/is_there_efficient_alternative_to_asio/ you indicated sync. is more performant than async. I believe I've read this elsewhere but it seems to contradict everything else on the internet. I'm inclined to believe you, after all you should know, but do you have any resources you could point me toward?

Firstly, with https://wg21.link/P2052, it is possible to write code more efficient than ASIO.

If the time to set up and tear down an async i/o is a non-trivial proportion of the total i/o time, sync will always be faster.

If you don't know how long the i/o will take (e.g. socket i/o, uncached spinning rust i/o), then async is probably worth it on average. If you do know how long the i/o will take (e.g. cached i/o, SSD i/o), then chances are very good you can write i/o code which is faster by going synchronous.

> Also there is the issue of benchmark tools like CrystalMark or fio. They seem to indicate throughput is higher with higher queue depths (like Q32T1 or Q8T8). If I understand queue depths correctly they are basically outstanding async calls. Is this correct? If so why do drives perform better with these async calls than synchronous sequential calls? Also, how would vectorized (scatter/gather) i/o fit into this equation?

Queue depth is just another way of saying how many 4Kb i/o being issued concurrently.

If you do a 128Kb i/o, the kernel will issue it to the SSD as 32x 4Kb. Or, QD32. This is because the kernel knows that SSDs can do many 4Kb i/o in parallel.

If you have 32 threads all doing 4Kb i/o, from the SSDs perspective it's no different. The kernel probably will do more work though than a single 128Kb i/o.

Async i/o might fit somewhere in between: not as much work as 32 threads all doing 4Kb i/o, but more work than a single 128Kb i/o. I say "might", because many kernels implement cached async file i/o using an internal thread pool. So you actually get the same as 32 user space threads.

Async file i/o for uncached i/o makes much more sense, as the kernel emits those as DMA buffers. Fairly low overhead. This is why I have been recommending to WG21 that we only care about async file i/o for uncached i/o such as sockets, pipes, and uncached files. For cached i/o like RDMA and cached files, almost always you really ought to be using sync i/o.

I hope that is useful, and thanks for the positive comments.
