### ISSUE TITLE
Nightly merge from develop to master is ignoring CI test failures.

### ISSUE THREAD

**Issue by cstratopoulos** [ned14/llfio#57]
Was working on a fresh build to test the changes from the discussion in #56 and ran into an issue where the project built fine but then a build failed when I tried to use the CMake installed version, looks like `algorithm/summarize.hpp` did not get added [here](https://github.com/ned14/llfio/blob/master/cmake/headers.cmake)

Was going to submit a patch myself but then saw the `# DO NOT EDIT, GENERATED BY SCRIPT` at the top--could be an issue in QuickCppLib maybe? Poked around quickly and my tentative understanding is that QuickCppLib generates the CMake install stuff using the `${PROJECT_NAME}_HEADERS` variable so maybe that's why it didn't make it in.

**Comment by ned14** [comment]
So, just to explain, the cache file does get updated correctly here locally by quickcpplib. Through habit, and not thinking, I didn't push it because it contains lots of other files not yet ready, specifically the new copy file content kernel offload function I'm currently writing (incidentally, writing a correct one of those is surprisingly hard).

As a totally separate issue, the nightly merge from develop to master branch isn't supposed to occur if there are CI failures, and the CI has been failing for weeks now due to some weird problem on Mac OS I'll need a real Mac to diagnose. I had thus been assuming master branch was always working, and apparently it is not.

So sorry about that. If you rerun cmake configure, it should automatically detect the stale directory tree and regenerate the cache files. If it does not, simply hose them out of the cmake directory.

Meanwhile I'll leave this issue open to remind me to go figure out why merge to master is ignoring CI.

**Comment by ned14** [comment]
Replaced with a github actions based mechanism instead, so closing.
