### ISSUE TITLE
LLFIO_HEADERS_ONLY_MEMFUNC_SPEC missing in .ipp files

### ISSUE THREAD

**Issue by duxi90** [ned14/llfio#61]
Methods with `LLFIO_HEADERS_ONLY_MEMFUNC_SPEC` in declaration are missing the same macro in .ipp files (e.g. `file_handle`, but lots more as well).

**Comment by ned14** [comment]
Yes, that's intentional. Some compilers don't like it. The current mix has no rationale, except "doesn't upset many compilers". It's completely adhoc.

**Comment by ned14** [comment]
At work we use header only LLFIO, so I'd expect I'd probably notice if it were broken.

Looking more closely, I don't understand why there is a multiple definition error for `signal_guard_destroy`. If it occurs, all the other signal guard functions ought to occur. That suggests that something weird is going on with the `SIGNALGUARD_FUNC_DECL` macro.

Also, `file_handle` doesn't implement `.clone()`, and `clone()` doesn't have that signature in any case because WG21 renamed it to `.reopen()`. That was start of this year.

Are you using an old LLFIO?

**Comment by duxi90** [comment]
You are right. Now that I've updated to a more recent commit, I'm not experiencing the same link error.

**Comment by ned14** [comment]
Cool, great!
